### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [JacobChwastek/SpaceInvaders#22]
1. Czy `background.jpg` i `ufo.png` mogłyby wylądować w `img`?
2. [To](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/bomb.py#L12) itp. jest średnie: robienie każdej bomby wiąże się z czytaniem z dysku. Moja propozycja: zrobić plik np. `images.py` z taką zawartością:
```python
import pygame

class Images:
    @staticmethod
    def set_up():
        Images.BOMB = pygame.image.load('img/bomb.png')
        ....
```
i z `main()` raz a dobrze wywołać `images.Images.set_up()`.
3. [To](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/button.py#L17) też przenieść do `Images`. Przy nazwie pliku i klasy się nie upieram.
4. [Tu](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/button.py#L6) lepiej `mouse_x, mouse_y = spam()`.
5. [Na to](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/colors.py#L1) jest lepsza recepta w 3. rozdziale Poradnika.
6. [Tutaj](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/enemyController.py#L7) wolałbym normalną klasę z konstruktorem i bez `staticmethod`. Da się?
7. Nie rozumiem, na co mam patrzeć: na `game.py` czy `main.py`. Zbędny plik wyrzucić, drugi przerobić zgodnie z receptą z 3. rozdziału.
8. Powtarzającą się stałą `(255, 255, 255)` nazwać.
9. [To](https://github.com/JacobChwastek/SpaceInvaders/blob/a40854152b26d2e78ec61c6de4f7abbe2de2583c/ship.py#L2) powyrzucać (3. rozdział).

**Comment by MarcinCiura** [comment]
2-3. Mój pomysł okrzepł w szczegółach. Proszę zajrzeć do 3. rozdziału.

**Comment by JacobChwastek** [comment]
Serdecznie dziękuję za wszystkie uwagi. Postaram się w jak najdokładniejszy sposób zaimplementować poprawki

**Comment by MarcinCiura** [comment]
5. Recepta była do bani. Poprawiłem, teraz jest dobra.

**Comment by JacobChwastek** [comment]
Zaimplementowałem w powyższym pull requestie zasugerowane przez Pana Doktora sugestnie. W najbliższym czasie zaimplementuje przykładowe  testy jednostkowe

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Co do kolorów — lepiej je nazwać wg zastosowania, nie wg zawartości (2. rozdział). Będzie się też lepiej grało w grę z bardziej wyszukanymi kolorami (koniec 3. rozdziału). Czekam na testy.

**Comment by JacobChwastek** [comment]
Dodałem do projektu bardziej wyszukane kolory korzystając z https://material.io/resources/color.
Zaimplementowałem też pierwsze test jednostkowe 
#24

**Comment by JacobChwastek** [comment]
Dodatkowo w imieniu swoim jak i moich kolegów i koleżanek chciałbym się dopytać co do stworzenia raportu określonego jako wymaganie w pliku Projekty_JS_2020_wytyczne.pdf

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. W testach `PLAYER_...` są nieużywane, a zamiast `DISPLAY_...` spokojnie wystarczą liczby. Wiersze `WIN = ...` i `pygame.init()` przenieść pod `if __name__ == '__main__':` (importowanie żadnego modułu nie powinno mieć żadnych skutków ubocznych; 3. rozdział).
Po tych zmianach będę mógł zaliczyć Pana projekt.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!

**Comment by MarcinCiura** [comment]
Aaa, jeszcze jedno: przydałyby się jeszcze ze dwa testy. Do czegokolwiek.

**Comment by JacobChwastek** [comment]
Dodałem parę nowych testów sprawdzających przypadki kolizji bomby z pozycją gracza oraz związane z ruchem bomby.  

Usunąłem nieużywane i zbędne zmienne. 

Nie wiem czy to poprawne podejście zamiast " WIN = ... i pygame.init() przenieść pod if __name__ == '__main__': " wrzucilem do funkcji setUp dla kazdej klasy testowej, gdyż miałem drobne problemy z poprawnym działaniem pygame w przypadku bezpośredniego umieszczenia podanych funkcji do warunku "if __name__ ".
Zmodyfikowalem  pygame.display.set tak aby nie wyswietlał zbednych okien.

**Comment by JacobChwastek** [comment]
W ten sposób zmieniłem położenie WIN =... oraz pygame.int()

https://github.com/JacobChwastek/SpaceInvaders/blob/035a829031d5655043d6c5c8378d8b6b27c905d8/test.py#L14

Nowe testy 

https://github.com/JacobChwastek/SpaceInvaders/blob/035a829031d5655043d6c5c8378d8b6b27c905d8/test.py#L52

https://github.com/JacobChwastek/SpaceInvaders/blob/035a829031d5655043d6c5c8378d8b6b27c905d8/test.py#L27

https://github.com/JacobChwastek/SpaceInvaders/blob/035a829031d5655043d6c5c8378d8b6b27c905d8/test.py#L36

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. LGTM. Gratuluję, jest Pan trzydziesty trzeci.
W wolnym czasie: [te trzy wiersze](https://github.com/JacobChwastek/SpaceInvaders/blob/035a829031d5655043d6c5c8378d8b6b27c905d8/test.py#L14) są: a) powtórzone; b) dość czasochłonne. Proponuję zaradzić obu problemom przez zrobienie klasy np. `TestBase(unittest.TestCase)`, a w niej metody klasowej `setUpClass()` z tymi wierszami, po czym klasy z testami niech dziedziczą z `TestClass`.
